version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=web_db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web_db
    volumes:
      - db_data:/var/lib/mysql
      - ./dacs2.sql:/docker-entrypoint-initdb.d/dacs2.sql

volumes:
  db_data:
